name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
      - name: Get current commit SHA
        id: get_commit
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Replace LOCALBUILD with commit SHA in locale
        run: |
          sed -i 's/LOCALBUILD/${{ env.COMMIT_SHA }}/g' _ark/ulti/locale_mod.dta
        env:
          COMMIT_SHA: ${{ env.COMMIT_SHA }}
      - name: Remove PS3 and Wii files
        run: |
          find . -name "*.*_ps3" -type f -delete
          find . -name "*.*_wii" -type f -delete
      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 5 -s 4073741823
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: GDRBUL-Xbox
          path: _build/xbox

  build_ps3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
      - name: Get current commit SHA
        id: get_commit
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Replace LOCALBUILD with commit SHA in locale
        run: |
          sed -i 's/LOCALBUILD/${{ env.COMMIT_SHA }}/g' _ark/ulti/locale_mod.dta
        env:
          COMMIT_SHA: ${{ env.COMMIT_SHA }}
      - name: Remove Xbox and Wii files
        run: |
          find . -name "*.*_xbox" -type f -delete
          find . -name "*.*_wii" -type f -delete
      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 5 -s 4073741823
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: GDRBUL-PS3
          path: _build/ps3

  build_wii_patcher_usa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
      - name: Get current commit SHA
        id: get_commit
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Replace LOCALBUILD with commit SHA in locale
        run: |
          sed -i 's/LOCALBUILD/${{ env.COMMIT_SHA }}/g' _ark/ulti/locale_mod.dta
        env:
          COMMIT_SHA: ${{ env.COMMIT_SHA }}
      - name: Remove Xbox and PS3 files
        run: |
          find . -name "*.*_xbox" -type f -delete
          find . -name "*.*_ps3" -type f -delete
      - name: Move songs_wii folder to _ark
        run: |
          mv _songs/songs_wii _ark/songs
      - name: Create necessary directories and copy files for patcher
        run: |
          mkdir -p ./_build/wii/ultimate_files/sys/
          mkdir -p ./_build/wii/ultimate_files/files/gen/
          mkdir -p ./_build/wii/iso
          mkdir -p ./_build/wii/wit
          cp dependencies/patch/main.dol ./_build/wii/ultimate_files/sys/main.dol
          cp dependencies/patch/setup.txt ./_build/wii/ultimate_files/setup.txt
          cp -r dependencies/wii-patcher/* ./_build/wii
          cp -r dependencies/wit/* ./_build/wii/wit
          cp -r iso/* ./_build/wii/iso

      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/wii/ultimate_files/files/gen -n "patch_wii" -e -v 5 -s 4073741823
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: GDRBUL-Wii-Patcher-USA
          path: _build/wii

  build_wii_riivolution:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          mkdir -p ./dependencies/riivolution-patch/gdrbul/
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
      - name: Get current commit SHA
        id: get_commit
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Replace LOCALBUILD with commit SHA in locale
        run: |
          sed -i 's/LOCALBUILD/${{ env.COMMIT_SHA }}/g' _ark/ulti/locale_mod.dta
      - name: Remove Xbox and PS3 files
        run: |
          find . -name "*.*_xbox" -type f -delete
          find . -name "*.*_ps3" -type f -delete
      - name: Move songs_wii folder to _ark
        run: |
          mv _songs/songs_wii _ark/songs

      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./dependencies/riivolution-patch/gdrbul -n "patch_wii" -e -v 5 -s 4073741823
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: GDRBUL-Wii-Riivolution
          path: dependencies/riivolution-patch
